openapi: 3.0.1
info:
  title: Stock Manager Swagger
  description: "This is a sample stock management application"
  termsOfService: http://swagger.io/terms/
  contact:
    email: email.akshay98@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://52.14.194.61:5521/api
  - url: http://localhost:5521/api
tags:
  - name: transaction
    description: Manage buy and sell transactions
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: security
    description: Manage securities
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths:
  /user:
    post:
      tags:
        - user
      summary: Add a new pet to the store
      operationId: addUser
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
    get:
      tags:
        - user
      summary: Get user
      operationId: getUser
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      security:
        - BearerAuth: []
  /user/topup:
    put:
      tags:
        - user
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TopUp"
      summary: Update user funds
      operationId: topUpUser
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      security:
        - BearerAuth: []

  /holding:
    get:
      tags:
        - holding
      summary: Get holdings
      operationId: getHoldings
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      security:
        - BearerAuth: []
  /transaction/buy/{ticker}:
    post:
      tags:
        - transaction
      parameters:
        - name: ticker
          in: path
          description: Ticker of the stock to buy
          required: true
          schema:
            type: string
      requestBody:
        description: Transaction properties need to be added
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Transaction"
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body
  /transaction/sell/{ticker}:
    post:
      tags:
        - transaction
      parameters:
        - name: ticker
          in: path
          description: Ticker of the stock to buy
          required: true
          schema:
            type: string
      requestBody:
        description: Transaction properties need to be added
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Transaction"
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body
  /transaction/{transactionId}:
    delete:
      tags:
        - transaction
      parameters:
        - name: transactionId
          in: path
          description: TransactionId of the transaction to delete
          required: true
          schema:
            type: string
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body
    put:
      tags:
        - transaction
      parameters:
        - name: transactionId
          in: path
          description: TransactionId of the transaction to update
          required: true
          schema:
            type: string
      requestBody:
        description: Transaction properties need to be added
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UpdateTransaction"
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body
    get:
      tags:
        - transaction
      parameters:
        - name: ticker
          in: path
          description: Ticker of stock whose transaction is needed to get
          required: true
          schema:
            type: string
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body

  /transaction:
    get:
      tags:
        - transaction
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body

  /security/:
    post:
      tags:
        - security
      operationId: "addSecurity"
      requestBody:
        description: Transaction properties need to be added
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Security"
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body
  /security:
    get:
      tags:
        - security
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body

  /security/{ticker}:
    delete:
      tags:
        - security
      operationId: "deleteSecurity"
      parameters:
        - name: ticker
          in: path
          description: Ticker of the stock to buy
          required: true
          schema:
            type: string
      responses:
        405:
          description: Invalid input
          content: {}
      security:
        - BearerAuth: []
      x-codegen-request-body-name: body
    put:
      tags:
        - security
      operationId: "updateSecurity"
      parameters:
        - name: ticker
          in: path
          description: Ticker of the stock to buy
          required: true
          schema:
            type: string
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SecurityPrice"
      summary: Update security price
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      security:
        - BearerAuth: []
components:
  schemas:
    User:
      type: object
      properties:
        userName:
          type: string
        mobile:
          type: string
      xml:
        name: User
    Transaction:
      type: object
      properties:
        shareCount:
          type: integer
          format: int64
      xml:
        name: Transaction
    Security:
      type: object
      properties:
        ticker:
          type: string
        totalShares:
          type: integer
          format: int64
        currentPrice:
          type: integer
          format: int64
      xml:
        name: Security
    TopUp:
      type: object
      properties:
        funds:
          type: integer
          format: int32
    SecurityPrice:
      type: object
      properties:
        currentPrice:
          type: integer
          format: int32
    UpdateTransaction:
      type: object
      properties:
        currentPrice:
          type: string
        shareCount:
          type: integer
          format: int32
        type:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
